version: "3.8"

services:
  llm-api:
    build: .
    ports:
      - "9090:9090"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
